ALTER TABLE business_profiles
    ADD COLUMN IF NOT EXISTS zelle_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS venmo_handle TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cashapp_handle TEXT NOT NULL DEFAULT '';
